# Generated by Django 5.2.1 on 2025-05-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_healthbotpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthTip',
        ),
    ]
