# Generated by Django 5.2.1 on 2025-05-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_healthtip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthBotPage',
        ),
    ]
